workflow_name: "{{ workflow_name }}"
environment_variables:
  - key: "ENV_VAR_1"
    value: "value_1"
iam_policy_file: "iam_policy.json"
home_regions:
  - provider: "aws"
    region: "us-east-1"
estimated_invocations_per_month: 1000000
constraints:
  hard_resource_constraints: # None for none
    cost:
      type: "absolute" # Absolute value as 'absolute' (in USD) or Percentage from deployment at home regions as 'percentage' (In fractions such as 1.1)
      value: COST_CONSTRAINT
    runtime:
      type: "absolute"
      value: RUNTIME_CONSTRAINT
    carbon:
      type: "absolute"
      value: CARBON_CONSTRAINT
  soft_resource_constraints: # None for none
    cost: null
    runtime: null
    carbon: null
  priority_order:
    - cost
    - runtime
    - carbon
regions_and_providers: # Either the user specify only allowed regions (which will override everything else)
  only_regions:
    - provider: "aws"
      region: "us-east-1"
  forbidden_regions:
    - provider: "aws"
      region: "us-east-2"
  providers:
    aws:
      config:
        timeout: 60
        memory: 128
